spring.application.name=aks-test

spring.datasource.url=${SPRING_DATASOURCE_URL:jdbc:postgresql://localhost:5432/employee_management}
spring.datasource.username=${SPRING_DATASOURCE_USERNAME:supr8sung}
spring.datasource.password=${SPRING_DATASOURCE_PASSWORD:Random@13}
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true