spring.application.name=aks-test



spring.datasource.url=jdbc:postgresql://localhost:5432/employee_management
spring.datasource.username=supr8sung
spring.datasource.password=Random@13

spring.jpa.hibernate.ddl-auto=create
spring.jpa.show-sql=true